services:
  # ──────────────────────────────────────────────────────────────────────────────
  # Tapyrus Core full node in dev-mode:
  #  • Uses GENESIS_BLOCK_WITH_SIG to auto-import a pre-built genesis block.
  #  • Reads all other settings from tapyrus.conf mounted below.
  #  • Exposes JSON-RPC on port 2377 for clients to connect.
  # ──────────────────────────────────────────────────────────────────────────────
  tapyrusd:
    image: tapyrus/tapyrusd:v0.6.1
    ports:
      - "2377:2377"  # Map container’s RPC port to the host for external access
    environment:
      # Provide a fixed genesis block hex (with federation signature) so we don't need a separate “genesis” container.
      # See: https://github.com/chaintope/tapyrus-core/blob/v0.6/doc/docker_image.md#dev-mode
      GENESIS_BLOCK_WITH_SIG: |
        0100000000000000000000000000000000000000000000000000000000000000000000002b5331139c6bc8646bb4e5737c51378133f70b9712b75548cb3c05f9188670e7440d295e7300c5640730c4634402a3e66fb5d921f76b48d8972a484cc0361e66ef74f45e012103af80b90d25145da28c583359beb47b21796b2fe1a23c1511e443e7a64dfdb27d40e05f064662d6b9acf65ae416379d82e11a9b78cdeb3a316d1057cd2780e3727f70a61f901d10acbe349cd11e04aa6b4351e782c44670aefbe138e99a5ce75ace01010000000100000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0100f2052a010000001976a91445d405b9ed450fec89044f9b7a99a4ef6fe2cd3f88ac00000000
    volumes:
      - ./tapyrus.conf:/etc/tapyrus/tapyrus.conf   # Dev-mode configuration (networkid, RPC creds, etc.)
      - ./data:/root/.tapyrus                      # Persist chain data and wallet between runs

  # ──────────────────────────────────────────────────────────────────────────────
  # Ruby-based Tapyrus client (interactive IRB):
  #  • Builds a small Ruby image with the `tapyrus` gem installed.
  #  • Waits for tapyrusd to be ready, then drops you into IRB with a `$client` instance.
  # ──────────────────────────────────────────────────────────────────────────────
  tapyrus-client:
    build:
      context: ./tapyrus-client
      dockerfile: Dockerfile.dev
    depends_on:
      - tapyrusd
    environment:
      # These must match the RPC settings in tapyrus.conf
      TAPYRUS_RPC_HOST:     "tapyrusd"        # Container hostname for the node
      TAPYRUS_RPC_PORT:     "2377"            # RPC port exposed by tapyrusd
      TAPYRUS_RPC_USER:     "rpcuser"         # RPC username (as defined in tapyrus.conf)
      TAPYRUS_RPC_PASSWORD: "rpcpassword"     # RPC password (as defined in tapyrus.conf)
    tty: true                            # Keep STDIN open so you can interact with IRB
    stdin_open: true
