# https://github.com/chaintope/tapyrus-core/blob/f94f0e3cebb1cf51f1ccd73d15fbc60d90553490/doc/docker_image.md
services:
  # This container runs tapyrus-genesis once to create a
  # genesis block signed by your dev “federation” keys.
  # It exits immediately, writing the block hex to stdout.
  #
  # Usage:
  #   docker compose run --rm genesis > data/genesis.1905960821
  genesis:
    image: tapyrus/tapyrusd:v0.6.1
    entrypoint: ["tapyrus-genesis"]
    command:
      - "-dev"                                         # dev‐mode genesis
      - "-time=1563342688"                             # fixed block timestamp
      - "-address=mmtAurzUTURFq9MSizWyj5sAkWzgqR8PBn"  # reward payout address
      - "-signblockpubkey=03af80b90d25145da28c583359beb47b21796b2fe1a23c1511e443e7a64dfdb27d"
      - "-signblockprivatekey=cUJN5RVzYWFoeY8rUztd47jzXCu1p57Ay8V7pqCzsBD3PEXN7Dd4"
    restart: "no"

  # The Tapyrus Core full node in dev‐mode:
  #  • loads your pre-generated genesis block from data/genesis.<networkid>
  #  • serves JSON-RPC for CLI calls and P2P for network tests
  tapyrusd:
    image: tapyrus/tapyrusd:v0.6.1
    entrypoint: ["tapyrusd"]
    command:
      - "-conf=/etc/tapyrus/tapyrus.conf"
      - "-server=1"            # enable JSON-RPC server
      - "-rpcbind=0.0.0.0"     # listen on all interfaces
      - "-rpcport=2377"        # match your published port
    volumes:
      - ./data:/root/.tapyrus
      - ./tapyrus.conf:/etc/tapyrus/tapyrus.conf:ro
    ports:
      - "2377:2377"
