FROM ruby:3.4.2-slim

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  build-essential \
  libssl-dev \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

RUN gem install tapyrus -v "~> 0.3.9" --no-document

RUN cat << 'EOF' > /root/.irbrc
require 'tapyrus'

$client = Tapyrus::RPC::TapyrusCoreClient.new(
  schema:   'http',
  host:     ENV.fetch('TAPYRUS_RPC_HOST')     { abort "Missing ENV[TAPYRUS_RPC_HOST]" },
  port:     ENV.fetch('TAPYRUS_RPC_PORT')     { abort "Missing ENV[TAPYRUS_RPC_PORT]" },
  user:     ENV.fetch('TAPYRUS_RPC_USER')     { abort "Missing ENV[TAPYRUS_RPC_USER]" },
  password: ENV.fetch('TAPYRUS_RPC_PASSWORD') { abort "Missing ENV[TAPYRUS_RPC_PASSWORD]" }
)

puts "→ $client ready (#{ENV['TAPYRUS_RPC_HOST']}:#{ENV['TAPYRUS_RPC_PORT']})"
EOF

WORKDIR /app

CMD ["irb", "-r", "tapyrus"]
